application/controllers/Connection.php

[IF02] Just the comment to test the branch

---

application/controllers/Connection.php

[IF03] This task is remove comment in connection

---

application/controllers/Connection.php

[IF04] Add comment to logout

---

application/controllers/Connection.php

[IFTest] This is for testing

---

application/controllers/Connection.php

[change] This is for chane

---

application/controllers/Welcome_IF.php
application/views/IF/pages/tutor/AddNew.php
application/views/IF/pages/tutor/detailTutor.php
application/views/IF/pages/tutor/editTutor.php
application/views/IF/pages/tutor/index.php

[TIF0011] Edite Tutor Pages

---

application/views/IF/pages/company/index.php

[IF0019]  IF0019 versoin 1.02

---

application/controllers/Welcome_IF.php

[IF0023] Add Welcome_IF into controller folder

---

application/views/login/login.php

[BIF004] "Edit on login page"

---

application/controllers/Welcome_IF.php

[BTF002] Resolve conflict

---

application/views/IF/pages/company/add.php
application/views/IF/pages/company/barChart.php
application/views/IF/pages/company/detail.php
application/views/IF/pages/company/edite.php

[IF0028] Edite on Company

---

application/views/IF/index.php

[IF0032] Update on home page

---

application/views/IF/supervisorDashboard/questionnair.php

[BIF0011] test questionnair

---

application/views/login/login.php

[IF0036] Edit login file

---

application/controllers/Welcome_IF.php
application/views/IF/pages/calendar/index.php
application/views/login/login.php

[IF0039] Solving Error login file

---

application/views/login/login.php

[TIF0020] login again

---

application/views/IF/menu/supervisorMenu.php

[BIF0015] Add notification on menu supervisor

---

application/views/IF/menu/studentMenu.php

[SIF0012] Edit menu versoin 1.02

---

application/views/IF/student/index.php

[BIF0019] Edit student home page

---

application/controllers/supervisor.php
application/views/IF/index.php
application/views/IF/supervisorDashboard/calendar/calendar.php

[BIF0021] Add calendar to supervisor dashboard

---

application/controllers/Welcome_IF.php
application/controllers/supervisor.php
application/views/IF/menu/supervisorMenu.php
application/views/IF/supervisorDashboard/calendar/calendar.php
application/views/IF/supervisorDashboard/index.php
application/views/IF/supervisorDashboard/student/index.php

[BIF0024] Add home page on supervisor dashboard

---

application/views/IF/supervisorDashboard/index.php

[BIF0025] Add count number on home page supervisor dashboard

---

application/views/IF/index.php
application/views/IF/menu/index.php
application/views/IF/menu/studentMenu.php
application/views/IF/pages/calendar/index.php
application/views/IF/pages/company/add.php
application/views/IF/pages/company/detail.php
application/views/IF/pages/company/edite.php
application/views/IF/pages/company/index.php
application/views/IF/pages/student/addstudent.php
application/views/IF/pages/student/comment.php
application/views/IF/pages/student/editstudent.php
application/views/IF/pages/student/index.php
application/views/IF/pages/student/viewstudent.php
application/views/IF/pages/supervisor/createSupervisor.php
application/views/IF/pages/supervisor/edit.php
application/views/IF/pages/supervisor/index.php
application/views/IF/pages/supervisor/view.php
application/views/IF/pages/tutor/AddNew.php
application/views/IF/pages/tutor/detailTutor.php
application/views/IF/pages/tutor/editTutor.php
application/views/IF/pages/tutor/index.php
application/views/IF/student/index.php
application/views/IF/student/worklog.php
application/views/IF/template/footer.php
assets/css/customCss.css

[SIF002] I has update on user ero and student

---

application/views/IF/index.php
application/views/IF/student/comment.php

[SIF003]I edit on index and comment of student

---

application/views/IF/pages/calendar/index.php
application/views/IF/pages/company/add.php
application/views/IF/pages/company/detail.php
application/views/IF/pages/company/edite.php
application/views/IF/pages/company/index.php
application/views/IF/pages/student/addComment.php
application/views/IF/pages/student/addstudent.php
application/views/IF/pages/student/comment.php
application/views/IF/pages/student/editstudent.php
application/views/IF/pages/student/index.php
application/views/IF/pages/student/viewstudent.php
application/views/IF/pages/supervisor/createSupervisor.php
application/views/IF/pages/supervisor/edit.php
application/views/IF/pages/supervisor/index.php
application/views/IF/pages/supervisor/view.php
application/views/IF/pages/tutor/AddNew.php
application/views/IF/pages/tutor/detailTutor.php
application/views/IF/pages/tutor/editTutor.php
application/views/IF/pages/tutor/index.php

[BIF0031] Edit on ERO dashboard

---

application/views/IF/student/calendarStu.php
application/views/IF/student/comment.php
application/views/IF/student/worklog.php
application/views/IF/supervisorDashboard/student/index.php

[BIF0033] Update on student dashboard

---

application/views/IF/menu/index.php
application/views/IF/menu/studentMenu.php
application/views/IF/menu/supervisorMenu.php
application/views/IF/menu/tutor.php

[BIF0034] Add tooltip to all menu

---

application/controllers/supervisor.php
application/views/IF/menu/supervisorMenu.php
application/views/IF/supervisorDashboard/calendar/calendar.php
application/views/IF/supervisorDashboard/questionnair.php
application/views/IF/supervisorDashboard/student/questionnairStudentList.php

[BIF0036] Push update supervisor dashboard version1.1

---

application/views/IF/index.php
application/views/IF/menu/index.php
application/views/IF/menu/studentMenu.php
application/views/IF/menu/supervisorMenu.php
application/views/IF/menu/tutor.php
application/views/IF/pages/calendar/index.php
application/views/IF/pages/company/index.php
application/views/IF/pages/student/index.php
application/views/IF/pages/supervisor/index.php
application/views/IF/pages/tutor/index.php
application/views/IF/supervisorDashboard/student/index.php
application/views/IF/template/footer.php
application/views/IF/tutorDashboard/company/index.php
application/views/IF/tutorDashboard/index.php
application/views/IF/tutorDashboard/student/index.php
application/views/IF/tutorDashboard/supervisor/index.php
application/views/IF/tutorDashboard/tutor/index.php
application/views/login/css/style.css
application/views/login/css/style1.css
application/views/login/login.php
assets/css/customCss.css

[TIF0029]edit content all page in project

---

application/controllers/Welcome_IF.php
application/models/Users_model.php
application/views/pages/tutor/AddNew.php
application/views/pages/tutor/editTutor.php
application/views/pages/tutor/index.php

[IF0064] crud tutor on ero team dashboard

---

application/controllers/Welcome_IF.php
application/models/Users_model.php
application/views/pages/supervisor/createSupervisor.php
application/views/pages/supervisor/edit.php
application/views/pages/supervisor/index.php
application/views/pages/supervisor/questionnair.php
application/views/pages/tutor/editTutor.php

[IF0070] Crud on supervisor

---

application/controllers/supervisor.php
application/models/Supervisor_model.php
application/views/supervisorDashboard/student/studentProfile.php

[DBI0027] select student detail on supervisor dashboard

---

README.md
application/views/student/worklog.php

[SIF007] I create file read me

---

README.md
application/config/database.php
application/views/student/worklog.php

[SIF009] i has update on work-log

---

application/config/database.php
application/controllers/tutorDas.php
application/views/pages/company/index.php
application/views/pages/index.php
application/views/pages/student/index.php
application/views/pages/supervisor/index.php
application/views/pages/tutor/index.php
application/views/student/comment.php
application/views/student/worklog.php
application/views/supervisorDashboard/student/index.php
application/views/supervisorDashboard/student/questionnairStudentList.php
application/views/supervisorDashboard/student/studentProfile.php
application/views/tutorDashboard/company/index.php
application/views/tutorDashboard/index.php
application/views/tutorDashboard/student/sDetail.php
application/views/tutorDashboard/student/studentWorkLog.php
application/views/tutorDashboard/student/viewWorkLog.php
application/views/tutorDashboard/supervisor/detail.php
application/views/tutorDashboard/supervisor/index.php
application/views/tutorDashboard/tutor/index.php
assets/css/skeleton-1.0.0.css

[SIF009] I has test and update all page interface

---

application/views/student/worklog.php

[SIF0014] update worklog

---

application/views/student/comment.php

[SIF0015] i update comment student

---

application/config/autoload.php
application/controllers/cStudent.php
application/models/m_worklog.php
application/views/student/worklogForm.php
sql/2018vc2gb (1).sql

[SIF0021] I has create file model for worklog

---

application/views/student/worklogForm.php

[SIF0023] I update worklog

---

README.md

[SIF0027] update on reade me file

---

README.md

[SIF0028] update on readme

---

README.md

[SIF0029] update readme

---

application/controllers/supervisor.php
application/models/Supervisor_model.php
application/views/supervisorDashboard/questionnair.php
application/views/supervisorDashboard/student/questionnairStudentList.php
sql/2018vc2gb (4).sql

[BIF0055] Commit get new resource
